name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go 1.25.0
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.0

      - name: Run go test
        run: go test ./...

      - name: Run coverage for tested packages
        run: go test ./internal/domain/example -coverprofile=coverage.out
